name: Deploy Docker Web App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build and Run Docker Container Locally
      run: |
        mkdir -p ~/docker-build
        cp -r * ~/docker-build/
        cd ~/docker-build
        docker build -t my-docker-web:latest .
        docker stop live-web-container || true
        docker rm live-web-container || true
        docker run -d --name live-web-container -p 80:80 my-docker-web:latest
