name: Deploy Docker Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Quick Docker Test
      run: |
        docker printf "Testing Docker Connection...\n"
        docker build -t my-docker-web:latest .
        docker run -d -p 8080:80 my-docker-web:latest
